# Generated by Django 5.1.2 on 2025-06-25 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_perfil_postulacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='usuario',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='cv_pdf',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='rut',
        ),
        migrations.AddField(
            model_name='perfil',
            name='apellidos',
            field=models.CharField(default='ApellidoDesconocido', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='curriculum_pdf',
            field=models.FileField(blank=True, null=True, upload_to='cv/'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil/'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1),
        ),
        migrations.AddField(
            model_name='perfil',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='perfil',
            name='nombres',
            field=models.CharField(default='NombreDesconocido', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='perfil',
            name='pais_residencia',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='perfil',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('CI', 'Cédula de Identidad'), ('PAS', 'Pasaporte')], max_length=3),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='carrera',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
