# Generated by Django 5.1.2 on 2025-06-25 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_usuario_perfil_user_remove_perfil_cv_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='anio_estudio',
            field=models.CharField(blank=True, choices=[('1', 'Primer año'), ('2', 'Segundo año'), ('3', 'Tercer año'), ('4', 'Cuarto año'), ('5', 'Quinto año')], max_length=2),
        ),
        migrations.AddField(
            model_name='perfil',
            name='area_estudio',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='perfil',
            name='carrera_pregrado',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='perfil',
            name='nivel_academico',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='perfil',
            name='pais_institucion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='perfil',
            name='situacion_academica',
            field=models.CharField(blank=True, choices=[('estudiante', 'Estudiante'), ('egresado', 'Egresado'), ('titulado', 'Titulado')], max_length=20),
        ),
    ]
