# Generated by Django 5.1.2 on 2025-06-26 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_perfil_anio_estudio_perfil_area_estudio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='estoy_buscando',
            field=models.CharField(blank=True, choices=[('practica', 'Práctica y/o pasantía'), ('trabajo', 'Trabajo')], max_length=20),
        ),
        migrations.AddField(
            model_name='perfil',
            name='experiencia_laboral',
            field=models.CharField(blank=True, choices=[('sin', 'Sin experiencia'), ('1', '1 año'), ('2', '2 años')], max_length=10),
        ),
    ]
