# Generated by Django 5.1.2 on 2025-06-26 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_perfil_estoy_buscando_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='nivel_excel',
            field=models.CharField(blank=True, choices=[('basico', 'Básico'), ('medio', 'Medio'), ('avanzado', 'Avanzado'), ('experto', 'Experto')], max_length=10),
        ),
        migrations.AddField(
            model_name='perfil',
            name='nivel_ingles',
            field=models.CharField(blank=True, choices=[('basico', 'Básico'), ('medio', 'Medio'), ('avanzado', 'Avanzado'), ('nativo', 'Nativo')], max_length=10),
        ),
    ]
