# Generated by Django 5.1.2 on 2025-06-26 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_perfil_nivel_excel_perfil_nivel_ingles'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaInteres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='perfil',
            name='estoy_buscando',
            field=models.CharField(blank=True, choices=[('practica', 'Práctica y/o pasantía'), ('trabajo', 'Trabajo')], max_length=20),
        ),
        migrations.AddField(
            model_name='perfil',
            name='areas_interes',
            field=models.ManyToManyField(blank=True, to='core.areainteres'),
        ),
    ]
