# Generated by Django 5.1.2 on 2025-06-27 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_areainteres_alter_perfil_estoy_buscando_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertalaboral',
            name='ciudad',
            field=models.CharField(default='Santiago', max_length=100),
        ),
        migrations.AddField(
            model_name='ofertalaboral',
            name='comuna',
            field=models.CharField(choices=[('Santiago', 'Santiago'), ('Las Condes', 'Las Condes'), ('Providencia', 'Providencia'), ('Maipú', 'Maipú'), ('La Florida', 'La Florida'), ('Puente Alto', 'Puente Alto'), ('Ñuñoa', 'Ñuñoa'), ('Recoleta', 'Recoleta'), ('La Reina', 'La Reina')], default='Santiago', max_length=100),
        ),
    ]
